main:
  - name: Posts
    pageRef: /posts
    weight: 10
    params:
      icon: posts

  - name: Archives
    pageRef: /archives
    weight: 60
    params:
      icon: archive

  # Example: parent item with dropdown submenu children
  #- name: More
  #  weight: 30
  #  params:
  #    icon: layers

  #- name: Categories
  #  weight: 1
  #  pageRef: /categories
  #  parent: More
  # params:
  #    icon: categories

  - name: Tags
    weight: 30
    pageRef: /tags
    #parent: More
    params:
      icon: tags      

  #- name: Series
  #  weight: 40
  #  pageRef: /series
  #  parent: More
  #  params:
  #    icon: bookmark

  #- name: Projects
  #  weight: 4
  #  pageRef: /projects
  #  parent: More
  #  params:
  #    icon: projects

  - name: About
    pageRef: /about
    weight: 70
    params:
      icon: about

# footer menu
footer:

  - name: RSS Feed
    url: /index.xml
    weight: 30
    params:
      icon: rss

# footer social link
social:
  - name: "GitHub"
    url: "https://github.com/willasaywhat"
    icon: "github"
  - name: "Mastodon"
    url: "https://infosec.exchange/@willasaywhat"
    icon: "mastodon"
  - name: "Bluesky"
    url: "https://bsky.app/profile/willasaywhat.bsky.social"
    icon: "bluesky"
  - name: "Threads"
    url: "https://www.threads.com/@willasaywhat"
    icon: "threads-w"
  - name: "Instagram"
    url: "https://instagram.com/willasaywhat"
    icon: "instagram"
